<a href="https://colab.research.google.com/github/malumisa/test/blob/main/Random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# additions
from sklearn.metrics import mean_squared_error
from sklearn.metrics import f1_score

In [21]:
# Load the data
df = pd.read_csv("/content/Result_Protein_Peptide_Combine.csv")

In [22]:
df.head()

visit_month  updrs_1  updrs_2  updrs_3  updrs_4  On  AADDTWEPFASGK  \
0            0     10.0      6.0     15.0      0.0   0      8984260.0   
1            6      8.0     10.0     34.0      0.0   0      8279770.0   
2           12     10.0     10.0     41.0      0.0   1      8382390.0   
3           36     17.0     18.0     51.0      0.0   1     10671500.0   
4            6      8.0      2.0     21.0      0.0   0      6177730.0   

   AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K  \
0                                           53855.6   
1                                           45251.9   
2                                           53000.9   
3                                           58108.4   
4                                           42682.6   

   AAFTEC(UniMod_4)C(UniMod_4)QAADK  AANEVSSADVK  ...  62329  62437  62723  \
0                         8579740.0          0.0  ...      0      0      0   
1                         8655890.0      49927.5  ...      0      0      0   
2                         8995640.0      45519.2  ...      0      0      0   
3                         9985420.0      52374.0  ...      0      0      0   
4                         3596660.0      25698.8  ...      0      0      0   

   62732  62792  63875  63889  64669  64674  65043  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 1449 columns]

In [23]:
# Define the target and feature variables
target_variable = ['updrs_1', 'updrs_2', 'updrs_3', 'updrs_4']
feature_variables = [x for x in df.columns if x != target_variable]

In [24]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df[feature_variables], df[target_variable], test_size=0.2, random_state=1)


In [25]:
# Create a Random Forest classifier instance
rf = RandomForestClassifier(n_estimators=2000, max_depth=10, min_samples_split=5, min_samples_leaf=3,random_state=1)

In [12]:
# Train the Random Forest classifier on the training data
#rf.fit(X_train, y_train)

In [26]:
# Train a separate Random Forest classifier for each target variable
models = {}
for target in target_variable:
    model = RandomForestClassifier(n_estimators=2000, max_depth=10, min_samples_split=5, min_samples_leaf=3,random_state=1)
    model.fit(X_train, y_train[target])
    y_pred = model.predict(X_test)
    f1 = f1_score(y_test[target], y_pred, average='weighted')
    print("F1 score for {} = {}".format(target, f1))
    models[target] = model

F1 score for updrs_1 = 0.21398433880550388
F1 score for updrs_2 = 0.16352074823385163
F1 score for updrs_3 = 0.058227774774078936
F1 score for updrs_4 = 0.6905123061114645


In [8]:
# Make predictions on the testing data
y_pred = rf.predict(X_test)

In [11]:
# Calculate the accuracy score
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

Mean Squared Error: 166.46962616822432


In [ ]:
# Evaluate the model using mean squared error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 166.46962616822432


In [ ]:
# Assuming y_pred and y_test are both arrays of shape (n_samples, n_classes)
# f1_scores = []
# for i in range(y_test.shape[1]):
#     f1 = f1_score(y_test[:,i], y_pred[:,i], average='weighted')
#     f1_scores.append(f1)

# mean_f1 = sum(f1_scores) / len(f1_scores)

# print(f"Mean F1 score: {mean_f1}")

In [ ]:
# Print the accuracy score
print(f"Accuracy: {accuracy}")

Accuracy: 0.13551401869158877


In [ ]:
# Print the confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[ 0 10  2  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 14  2  0  0  1  1  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 17  5  2  0  1  3  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 13  2  0  2  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  3  0  0  1  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  2  1  0  2  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  1  0  0  0  2  0  1  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  4  3  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  1  0  1  1  5  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  1  0  1  3  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  1  0  1  1  4  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  1  1  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  4  2  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  1  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
